# Generated by Django 4.2.5 on 2023-09-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/blogs/%Y/%m/%d'),
        ),
    ]
