# Generated by Django 4.2.5 on 2023-09-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
