# Generated by Django 4.2.5 on 2023-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='photos/blogs/news_default.png', null=True, upload_to='photos/blogs/%Y/%m/%d'),
        ),
    ]
